services:
  angular-vivero:
    build: .
    ports:
      - "4200:4200"   # Exponemos el puerto 4200 para desarrollo
      #- "4200:80"   # Exponemos el 80 de NGINX en el puerto 4200 local - esto en modo producción
    volumes:
      - ./src:/app/src # Sincronizamos el código fuente para desarrollo continuamente
      - angular_node_modules:/app/node_modules #Node modules persiste en un volumen docker
    command: npx ng serve --host 0.0.0.0 --poll 2000 && echo '✅ Angular corriendo en http://localhost:4200'"
    restart: always

volumes:
  angular_node_modules: